
underlay:
    loopback_ip: 172.1.1.2
    local:
        asn: 65001
    neighbors:

      - interface: xe-0/0/3
        name: leaf-02
        asn: 65003
        peer_ip: 100.0.1.11
        local_ip: 100.0.1.10

      - interface: xe-0/0/1
        name: spine-01
        asn: 65000
        peer_ip: 100.0.1.2
        local_ip: 100.0.1.3

      - interface: xe-0/0/2
        name: leaf-01
        asn: 65002
        peer_ip: 100.0.1.9
        local_ip: 100.0.1.8

      - interface: xe-0/0/0
        name: spine-01
        asn: 65000
        peer_ip: 100.0.1.0
        local_ip: 100.0.1.1
