---
- name: validate ip fabric
  hosts: all
  connection: local
  gather_facts: false
  tasks:
############################################################
  - name: inclued Juniper junos
    include_role:
      name: Juniper.junos
############################################################
  - name: check IP Fabric Interfaces Admin Status
    include_role:
      name: check-underlay-if
############################################################
  - name: check ip reachability between underlay interfaces
    include_role:
      name: ping
############################################################
  - name: check lldp for underlay interfaces
    include_role:
      name: check-lldp
############################################################
  - name: check  IP Fabric ebgp & MP-iBGP
    include_role:
      name: check-bgp
############################################################
  - name: check vtep interfaces
    include_role:
      name: check-vtep
############################################################
  - name: check tenants vlans
    include_role:
      name: check-vlan
###########################################################
- name: check leaf to compute LACP Interfaces 
  hosts: leaf
  connection: local
  gather_facts: false
  roles:
  - check-lacp
###########################################################
- name: check spine-spine, spine-contrail MP-iBPG
  hosts: spine
  connection: local
  gather_facts: false
  roles:
  - check-spine-ibgp
###########################################################
- name: collect cli
  hosts: all
  connection: local
  gather_facts: false
  tasks:
  - name: inclued Juniper junos
    include_role:
      name: Juniper.junos
  - name: collect cli
    include_role:
      name: collect-commands
###########################################################

